### ISSUE TITLE
vendor assets encoding

### ISSUE THREAD

**Issue by MarkMT** [jschniper/ember-cli-deploy-cloudfiles#1]
I've been able to upload my assets to Cloud Files ok, but I'm having  a problem getting the files to loaded by the browser properly - some of them seem to get binary encoded for some reason.

I raised the issue at https://github.com/ember-cli/ember-cli-deploy/issues/191 and after some advice was able to get the app working off s3 instead. However the problem with Cloud Files persists.

I don't know that the problem is caused by ember-deploy-cloudfiles specifically, since I've tried manually uploading the files and still see the same problem. So I've also raised the issue on the Cloud Files forum at https://community.rackspace.com/developers/f/7/t/5450. However whatever the underlying issue is, it does seem to affect users of this plug-in.

**Comment by jschniper** [comment]
Can you try adding `gzip: false` inside the assets configuration inside your config/deploy.js?

For example:
```
production: {
  store: {
    ...
  },
  assets: {
    gzip: false,
    type: 'cloudfiles',
    region: 'ORD',
    ...
  }
}
```

**Comment by jschniper** [comment]
My apology, I just reread what you posted in ember-cli-deploy and saw that you are using specifying `gzip: false`. I'll keep digging and see what I can find.

**Comment by jschniper** [comment]
I upgraded to the latest version of ember-cli-deploy and did a bit of testing:

The `gzip: false` flag is necessary otherwise I end up with a file that looks a lot like the one you referenced in the ember-cli-deploy issue. That being said, if I specify the flag everything seems to work as expected. It might be worth trying to create a new container in Rackspace and starting fresh in order to bypass any cached versions on the server. I'm honestly a bit stumped right now if you've been specifying `gzip: false` since the get go but I'll keep looking.

**Comment by MarkMT** [comment]
Thanks for confirming the `gzip: false` requirement. Curiously I needed the exact opposite setting to make the s3 adapter work. I have Rackspace investigating the issue at the moment and will report here what I learn.

Also, just for completeness, here is some additional info I posted on the Rackspace forum:

> the problem seems to be associated not with the file itself, but with its name. The filenames above are fingerprinted by ember by appending an MD5 checksum. If I make a copy of the file that I'm having problems with but give it a different name, even by one character, and then upload it either using pkgcloud or manually, I can load the resulting file in my browser without any problem.

**Comment by MarkMT** [comment]
Rackspace weren't very helpful and were unable to provide a credible explanation of what was going on, but in the meantime the problem seems to have resolved itself (?!), for now at least. The question of why `gzip: false` is required remains unclear.

**Comment by jschniper** [comment]
I'm thinking that maybe S3 includes the proper headers to let the browser handle compressed files while Rackspace does not (at least by default). I'll have to check into it some more.
